### ISSUE TITLE
Font face fragmentation

### ISSUE THREAD

**Issue by vinzv** [openSUSE/www.opensuse.org#3]
Why the use of three different font faces in the top area already?

![image](https://user-images.githubusercontent.com/74432/85958146-84f1ed80-b993-11ea-9878-d4e20fe88191.png)

**Comment by guoyunhe** [comment]
The fonts are "Source Sans Pro", "Source Sans Pro Light" and "Source Code Pro". All the fonts are defined in original openSUSE branding guideline.

The big heading is a typewriter animation. I want to add some "geek" flavor into it, to match "sysadmins, developers".  So I chose a monospace font similar to the one used in terminals and editors.

For the distro description, it is "Lead" text defined by Bootstrap, which by default has bigger font size and thinner font weight.

I don't see it a problem. Many modern web design uses more than three font face:

![image](https://user-images.githubusercontent.com/5836790/85977058-813a8700-b9e4-11ea-8448-ec8f3d8ed4eb.png)

![image](https://user-images.githubusercontent.com/5836790/85977560-83e9ac00-b9e5-11ea-9aa6-c8bc0ac1b0d9.png)

**Comment by vinzv** [comment]
Okay, thanks for explaining!
