### ISSUE TITLE
Background animation

### ISSUE THREAD

**Issue by vinzv** [openSUSE/www.opensuse.org#4]
![image](https://user-images.githubusercontent.com/74432/85958197-f2058300-b993-11ea-8ffc-286d70d829bb.png)

The background animation gives quite a handful of problems:

1. The colors used are not openSUSE related in any way
2. CPU usage spikes unecessarily. I have one CPU core at nearly 100% just by this animation.
3. It breaks the overall clean and pragmatic visuality.
4. Text placed above it gets hard to read.

**Comment by guoyunhe** [comment]
Removed
